author: "GroG"
categories: ["timer", "clock"]
dependencies: null
description: "A timer for scheduled events"
installed: true
license: "MIT"
online: false
platform: "node"
platformVersion: "v20.9.0"
title: "Clock"
typeKey: "Clock"
version: "0.0.1"
visible: true
