# managed
"""First-user enrollment endpoints — generated by create_app.py.

Emitted into apps that declare ``app.auth.bootstrap: first_user_claim``
in their yml. A fresh runtime starts with NO users; the operator
establishes the first account via the UI which calls:

  * ``GET  /v1/auth/has-users``         — unauthenticated. Returns
                                          ``{"exists": bool}``. The
                                          Login page uses this on mount
                                          to decide whether to render
                                          the claim form or sign-in.
  * ``POST /v1/auth/claim-first-user``  — unauthenticated. Body
                                          ``{email, password}``.
                                          Atomically refuses if any
                                          user already exists.

Per-app role logic plugs in via ``event_handlers.on_first_user(user,
db)`` — mutate ``user["roles"]`` (and anything else, like creating a
tenant row) there. If the hook isn't implemented (or doesn't set
``user["roles"]``), the user is granted ``DEFAULT_ROLES`` declared
below — which the yml's ``app.auth.first_user_default_roles`` sets at
generation time.
"""
import logging
import re
import time
import uuid
from typing import Callable, List

from auth import create_auth_dependencies
from auth.local_auth import USERS_TABLE
from auth.session_manager import hash_refresh_token
from config import create_app_settings
from database.interface import DatabaseAdapter
from fastapi import APIRouter, Depends, FastAPI, HTTPException
from pydantic import BaseModel, Field, field_validator

from invoker import safe_invoke
from robotlab_x.models.config import Config


logger = logging.getLogger(__name__)

settings, config_provider = create_app_settings("robotlab_x", Config)
auth_deps = create_auth_dependencies(config_provider)


# Pragmatic email shape — local-part@domain. Not RFC 5322 compliant
# (that's a rabbit hole) but rejects anything obviously not an
# address. The UI's <input type="email"> handles user-facing
# validation; this is just a server-side safety net.
_EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")

# Default roles granted to the first claimer when ``on_first_user``
# isn't implemented (or doesn't assign roles). Set via the yml field
# ``app.auth.first_user_default_roles``.
DEFAULT_ROLES: List[str] = ["Admin"]


class HasUsersResponse(BaseModel):
    exists: bool = Field(..., description="True if at least one user has been created on this runtime")


class ClaimFirstUserRequest(BaseModel):
    email: str = Field(..., description="Email address — used as the user id and login username")
    password: str = Field(..., min_length=8, description="Initial password (minimum 8 characters)")

    @field_validator("email")
    @classmethod
    def _check_email(cls, v: str) -> str:
        v = v.strip().lower()
        if not _EMAIL_RE.match(v):
            raise ValueError("not a valid email address")
        return v


class ClaimFirstUserResponse(BaseModel):
    access_token: str
    refresh_token: str
    token_type: str = "bearer"


def register_first_user_routes(app: FastAPI, get_db_provider: Callable) -> None:
    """Mount the first-user enrollment routes on ``app``."""
    router = APIRouter()

    @router.get(
        "/auth/has-users",
        response_model=HasUsersResponse,
        description=(
            "Probe whether this runtime has any user accounts. Used by the "
            "Login page to decide whether to render the first-user claim "
            "form or a normal sign-in form. Unauthenticated — the answer "
            "leaks no sensitive state (it only says whether *someone* has "
            "set up this runtime)."
        ),
    )
    def has_users(db: DatabaseAdapter = Depends(get_db_provider)) -> HasUsersResponse:
        rows = db.get_all_items(USERS_TABLE) or []
        return HasUsersResponse(exists=len(rows) > 0)

    @router.post(
        "/auth/claim-first-user",
        response_model=ClaimFirstUserResponse,
        description=(
            "Claim the first user account on a fresh runtime. Succeeds only "
            "when the user table is empty; subsequent calls 409. Calls "
            "event_handlers.on_first_user(user, db) so the app can assign "
            "roles or run any per-app setup. Falls back to "
            "first_user_default_roles when the hook is absent."
        ),
    )
    def claim_first_user(
        req: ClaimFirstUserRequest,
        db: DatabaseAdapter = Depends(get_db_provider),
    ) -> ClaimFirstUserResponse:
        # Atomic-ish re-check inside the handler. TinyDB/lowdb is GIL-
        # serialised so two concurrent claims race only between the
        # check below and the insert; the insert is the final safety
        # net (would conflict on the same id).
        existing = db.get_all_items(USERS_TABLE) or []
        if existing:
            raise HTTPException(
                status_code=409,
                detail="A user already exists on this runtime — claim-first-user is closed.",
            )

        user_id = str(req.email).lower()
        now_ms = int(time.time() * 1000)

        password_hash = auth_deps.auth.generate_hash(req.password)
        user = {
            "id": user_id,
            "email": user_id,
            "email_verified": True,  # operator established themselves; no email loop
            "password_hash": password_hash,
            "roles": [],
            "status": "active",
            "auth_provider": "local",
            "is_mfa_enabled": False,
            "created": now_ms,
            "modified": now_ms,
        }

        # Per-app hook — mutate user in place. Common: set roles,
        # create a tenant row, link to an external profile.
        safe_invoke(
            "robotlab_x.event_handlers",
            "on_first_user",
            [user, db],
        )

        # Fallback if the hook didn't set roles (or wasn't implemented).
        if not user.get("roles"):
            user["roles"] = list(DEFAULT_ROLES)

        try:
            db.insert_item(USERS_TABLE, user_id, user)
        except Exception as e:
            logger.exception("claim-first-user: insert failed for %s", user_id)
            raise HTTPException(status_code=500, detail=f"could not create user: {e}")

        # Mint a token via the same path /v1/login uses, so the response
        # shape + refresh-token semantics stay identical.
        token = auth_deps.auth.authenticate(user_id, req.password)
        if not token:
            logger.error("claim-first-user: authenticate failed immediately after insert for %s", user_id)
            raise HTTPException(status_code=500, detail="user created but token mint failed")

        refresh_token = str(uuid.uuid4())
        refresh_token_hash = hash_refresh_token(refresh_token)
        session_id = f"sess_{uuid.uuid4().hex[:16]}"
        # Session TTL default = 24h. The /v1/login handler reads this
        # from event_handlers.on_get_auth_session_ttl_seconds; the claim
        # flow is rare enough that hard-coding the same default keeps
        # this file self-contained.
        expires_at = now_ms + (24 * 60 * 60 * 1000)
        auth_session = {
            "id": session_id,
            "user_id": user_id,
            "tenant_id": user.get("tenant_id"),
            "refresh_token_hash": refresh_token_hash,
            "status": "active",
            "created": now_ms,
            "expires_at": expires_at,
            "last_used_at": now_ms,
            "user_agent": None,
            "ip_address": None,
        }
        try:
            db.insert_item("auth_session", session_id, auth_session)
        except Exception as e:
            logger.warning("claim-first-user: auth_session insert fell back to update: %s", e)
            db.update_item("auth_session", session_id, auth_session)

        logger.info(
            "claim-first-user: established %s with roles=%s",
            user_id, user.get("roles"),
        )
        return ClaimFirstUserResponse(
            access_token=token,
            refresh_token=refresh_token,
            token_type="bearer",
        )

    app.include_router(router, prefix="/v1", tags=["Auth"])
