openapi: 3.0.3
info:
  title: API Documentation
  version: 1.0.0
servers:
  - url: http://localhost:3001/v1
    description: Local development server
components:
  schemas:
    $schema: http://json-schema.org/draft-07/schema#
    definitions:
      Config:
        properties:
          fetch:
            type: object
          host:
            type: string
          proxy:
            type: boolean
        type: object
    properties:
      abortController: {}
      config:
        $ref: '#/definitions/Config'
      fetch:
        type: object
    type: object
paths:
  /startService:
    put:
      summary: Executes startService method
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: null
      responses:
        '200':
          description: startService method executed successfully
  /connect:
    put:
      summary: Executes connect method
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: string
            example: null
      responses:
        '200':
          description: connect method executed successfully
  /moveTo:
    put:
      summary: Executes moveTo method
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: integer
            example: null
      responses:
        '200':
          description: moveTo method executed successfully
  /disconnect:
    put:
      summary: Executes disconnect method
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: null
      responses:
        '200':
          description: disconnect method executed successfully
  /getPorts:
    put:
      summary: Executes getPorts method
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: null
      responses:
        '200':
          description: getPorts method executed successfully
  /getBoardInfo:
    put:
      summary: Executes getBoardInfo method
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: null
      responses:
        '200':
          description: getBoardInfo method executed successfully
  /createPins:
    put:
      summary: Executes createPins method
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: null
      responses:
        '200':
          description: createPins method executed successfully
  /getPins:
    put:
      summary: Executes getPins method
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: null
      responses:
        '200':
          description: getPins method executed successfully
  /write:
    put:
      summary: Executes write method
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: integer
                - type: integer
            example: null
      responses:
        '200':
          description: write method executed successfully
  /toJSON:
    put:
      summary: Executes toJSON method
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: null
      responses:
        '200':
          description: toJSON method executed successfully
tags: []
