typeKey: "Servo"
title: "Servo"
platform: "node"
platformVersion: "v20.9.0"
description: "Servo control"
version: "0.0.1"
visible: true
interfaces:
  restAPI:
    - endpoint: "/api/v1/resource"
      method: "GET"
      description: "Retrieves list of resources."
author: "GroG"
license: "MIT"
categories:
- "servo"
dependencies: null
