author: "GroG"
categories: -"servo"
dependencies: null
description: "Servo control"
installed: true
license: "MIT"
platform: "node"
platformVersion: "v20.9.0"
title: "Servo"
typeKey: "Servo"
version: "0.0.1"
visible: true
