typeKey: "Arduino"
title: "Arduino"
platform: "node"
platformVersion: "v20.9.0"
description: "A great microcontroller project"
version: "0.0.1"
interfaces:
  restAPI:
    - endpoint: "/api/v1/resource"
      method: "GET"
      description: "Retrieves list of resources."
author: "GroG"
license: "MIT"
categories:
- "microcontroller"
- "servo"
- "sensor"
- "i2c"
dependencies: null
