typeKey: "WebRTC"
title: "WebRTC Server"
platform: "browser"
platformVersion: null
description: "WebRTC server for video streaming from webcam"
version: "0.0.1"
interfaces:
  restAPI:
    - endpoint: "/api/v1/resource"
      method: "GET"
      description: "Retrieves list of resources."
author: "GroG"
license: "MIT"
language: "JavaScript"
categories:
- "web"
- "ui"
dependencies: null