author: "GroG"
categories:
  - "web"
  - "ui"
  - "vr"
  - "headset"
dependencies: null
description: "WebXR interface for virtual reality and augmented reality."
license: "MIT"
platform: "node"
platformVersion: "v20.9.0"
title: "WebXR Interface"
typeKey: "WebXR"
version: "0.0.1"
visible: true
