author: "GroG"
categories:
  - "web"
  - "ui"
  - "vr"
  - "headset"
dependencies: null
description: "WebXR interface for virtual reality and augmented reality."
license: "MIT"
platform: "browser"
platformVersion: null
title: "WebXR Interface"
typeKey: "WebXR"
version: "0.0.1"
visible: true
