typeKey: "Proxy"
title: "Proxy"
platform: "node" # should be null or Proxy or a new proxy field
platformVersion: "v20.9.0"
description: "Proxy service"
version: "0.0.1"
interfaces:
  restAPI:
    - endpoint: "/api/v1/resource"
      method: "GET"
      description: "Retrieves list of resources."
author: "GroG"
license: "MIT"
categories:
- "proxy"
dependencies: null
