typeKey: "Unknown"
title: "Unknown"
platform: "node"
platformVersion: "v20.9.0"
description: "Unknown service type."
version: "0.0.1"
interfaces:
  restAPI:
    - endpoint: "/api/v1/resource"
      method: "GET"
      description: "Retrieves list of resources."
author: "GroG"
license: "MIT"
categories:
- "programming"
dependencies: null