author: "GroG"
categories: ["files", "audioplayer", "audio", "sound"]
dependencies: null
description: "An audio player for any audio file"
installed: true
license: "MIT"
online: false
platform: "node"
platformVersion: "v20.9.0"
title: "Audio Player"
typeKey: "AudioPlayer"
version: "0.0.1"
visible: true
