author: "GroG"
categories: ["speech", "tts"]
dependencies: null
description: "AWS Polly Text-to-Speech"
installed: true
license: "MIT"
online: true
platform: "node"
platformVersion: "v20.9.0"
title: "AWS Polly Text-to-Speech"
typeKey: "Polly"
version: "0.0.1"
visible: true
