typeKey: "WebRTC"
title: "WebRTC Server"
platform: "python"
platformVersion: null
description: "WebRTC server for video streaming from webcam"
version: "0.0.1"
requirements: "pip install -r requirements.txt"
cmd: "python"
args: ["start.py"]
author: "GroG"
license: "MIT"
categories: ["web", "ui"]
dependencies: null
