typeKey: "PySpeechRecognition"
title: "Speech Recognition"
platform: "python"
platformVersion: "3.8"
description: "Speech recognition service"
version: "0.0.1"
requirements:
  SpeechRecognition: ">=3.10.4"
  PyAudio: ">=0.2.14"
repoRequirements:
  - "Proxy"
  - "PySpeechRecognition"
visible: true
args: ["-u","proxy.py", "-i", "{{name}}", "-c", "{{serviceUrl}}"] # -u unbuffered output
author: "GroG"
license: "MIT"
categories: ["audio", "microphone", "sound", "speech"]
dependencies: null
