typeKey: "PyAIML"
title: "AIML ChatBot"
platform: "python"
platformVersion: "3.10"
description: "AIML (Artificial Intelligence Markup Language) is a natural language processing (NLP) framework for creating conversational agents."
version: "0.0.1"
requirements:
  vosk: ">=0.3.45"
  sounddevice: ">=0.4.7"
repoRequirements:
  - "Proxy"
  - "PyAIML"
visible: true
args: ["-u","proxy.py", "-i", "{{name}}", "-c", "{{serviceUrl}}"] # -u unbuffered output
author: "GroG"
license: "MIT"
categories: ["ai", "intelligence", "aiml", "chatbot"]
dependencies: null
