author: "GroG"
categories: ["programming"]
dependencies: null
description: "A node interface for programming"
installed: true
license: "MIT"
online: false
platform: "node"
platformVersion: "v20.9.0"
title: "Node"
typeKey: "Node"
version: "0.0.1"
visible: true
