typeKey: "Node"
title: "Node Service"
platform: "node"
platformVersion: null
description: "Node programming interface"
version: "0.0.1"
cmd:
args:
cwd: null
interfaces:
  restAPI:
    - endpoint: "/api/v1/resource"
      method: "GET"
      description: "Retrieves list of resources."
author: "GroG"
license: "MIT"
categories:
- "web"
- "testing"
- "ui"
dependencies: null