author: "GroG"
categories: ["ai", "llm"]
dependencies: null
description: "Ollama installer and interface"
installed: true
license: "MIT"
platform: "node"
platformVersion: "v20.9.0"
title: "Ollama"
typeKey: "Ollama"
version: "0.0.1"
visible: true
