typeKey: "MyRobotLab"
title: "My Robot Lab"
platform: "java"
platformVersion: "11"
description: "My Robot Lab Runtime"
version: "0.0.1"
interfaces:
  restAPI:
    - endpoint: "/api/v1/resource"
      method: "GET"
      description: "Retrieves list of resources."
author: "GroG"
license: "MIT"
language: "Java"
categories:
- "web"
- "http"
- "service manager"
- "framework"
dependencies: null