typeKey: "OpenCV"
title: "OpenCV Service"
platform: "python"
platformVersion: null # minimum version ?
description: "OpenCV pipeline"
version: "0.0.1"
cmd: "python"
args: ["-u","OpenCV.py", "-i", "{{name}}", "-c", "{{serviceUrl}}"] # -u unbuffered output
cwd: null
interfaces:
  restAPI:
    - endpoint: "/api/v1/resource"
      method: "GET"
      description: "Retrieves list of resources."
requirements:
  opencv-python: ">=4.10.0"
repoRequirements:
  - "rlx-pkg-proxy"
  - "rlx-pkg-opencv"
author: "GroG"
license: "MIT"
categories:
- "web"
- "testing"
- "ui"
dependencies: null
