typeKey: "OpenCV"
title: "OpenCV Service"
platform: "python"
platformVersion: null # minimum version ?
description: "OpenCV pipeline"
version: "0.0.1"
visible: true
cmd: "python"
args: ["-u","proxy.py", "-i", "{{name}}", "-c", "{{serviceUrl}}"] # -u unbuffered output
cwd: null
interfaces:
  restAPI:
    - endpoint: "/api/v1/resource"
      method: "GET"
      description: "Retrieves list of resources."
requirements:
  opencv-python: ">=4.10.0"
  scikit-learn: ">=1.5.0"
  joblib: ">=1.4.2"
repoRequirements:
  - "Proxy"
  - "OpenCV"
author: "GroG"
license: "MIT"
categories:
- "web"
- "testing"
- "ui"
dependencies: null
