args:
  - -u
  - proxy.py
  - -i
  - "{{name}}"
  - -c
  - "{{serviceUrl}}"
author: GroG
categories:
  - web
  - testing
  - ui
cmd: python
cwd: /home/gperry/mrl/robotlab-x/server/express/public/repo/opencv
dependencies: null
description: OpenCV pipeline
installed: false
license: MIT
platform: python
platformVersion: null
repoRequirements:
  - Proxy
  - OpenCV
requirements:
  joblib: ">=1.4.2"
  opencv-python: ">=4.10.0"
  scikit-learn: ""
title: OpenCV Service
typeKey: OpenCV
version: 0.0.1
visible: true
