typeKey: "WebRTC"
title: "WebRTC Server"
platform: "python"
platformVersion: null
description: "WebRTC server for video streaming from webcam"
version: "0.0.1"
cmd: "python"
args: ["start.py"]
cwd: null
interfaces:
  restAPI:
    - endpoint: "/api/v1/resource"
      method: "GET"
      description: "Retrieves list of resources."
author: "GroG"
license: "MIT"
language: "JavaScript"
categories:
- "web"
- "ui"
dependencies: null