typeKey: "TestRosService"
title: "Test Ros Service"
platform: "ros"
platformVersion: null
description: "Ros test service for testing!"
version: "0.0.1"
cmd:
args:
cwd: null
interfaces:
  restAPI:
    - endpoint: "/api/v1/resource"
      method: "GET"
      description: "Retrieves list of resources."
author: "GroG"
license: "MIT"
categories:
- "web"
- "testing"
- "ui"
dependencies: null