name: Linux Arm64 Build and Package RobotLab-X

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.18.0]

    env:
      CI: false


    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Print system info
        run: |
          uname -a
          lscpu
          cat /etc/os-release

      - name: Verify Version Input and Set Environment Variable
        run: |
          echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          echo "Passed version is: ${{ inputs.version }}"
          echo "All environment variables:"
          printenv
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install-all

      - name: Install Cross-Compilation Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y libc6-dev-arm64-cross linux-libc-dev-arm64-cross \
                                  g++-aarch64-linux-gnu

      - name: Run ESLint
        run: yarn lint || true

      - name: Build and Install Client
        run: |
          yarn build-client
          yarn install-client

      - name: Build Server
        run: yarn build-server

      - name: Run tests
        run: |
          cd server
          yarn test

      - name: PreBuild clean
        run: rm -rf ~/.npm/_prebuilds

      - name: Package
        run: yarn package-linux-arm64

      - name: Make output file executable
        run: chmod +x "dist/packages/robotlab-x-${{ env.VERSION }}-arm64.AppImage"

      - name: Create versioned folder and move artifact
        run: |
          mkdir -p "dist/packages/robotLab-X-${{ env.VERSION }}"
          mv "dist/packages/robotlab-x-${{ env.VERSION }}-arm64.AppImage" "dist/packages/robotLab-X-${{ env.VERSION }}/"

      - name: Zip the versioned folder
        run: |
          cd dist/packages
          zip -r "robotlab-X-${{ env.VERSION }}-linux-arm64.zip" "robotLab-X-${{ env.VERSION }}"

      - name: List dist/packages contents
        run: ls -l dist/packages

      - name: Upload to Amazon S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          aws s3 cp "dist/packages/robotlab-X-${{ env.VERSION }}-linux-arm64.zip" "s3://robotlab-x-repo/robotlab-X-${{ env.VERSION }}-linux-arm64.zip"


