name: Linux Build and Package RobotLab-X

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.18.0]

    env:
      CI: false

    steps:
      - name: Verify Version Input and Set Environment Variable
        run: |
          echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          echo "Passed version is: ${{ inputs.version }}"
          echo "All environment variables:"
          printenv
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install-all

      - name: Run ESLint
        run: yarn lint || true

      - name: Build Server
        run: yarn build-server

      - name: Run tests
        run: |
          cd server
          yarn test

      - name: Package
        run: yarn package-linux

      - name: List dist/packages contents
        run: ls -l dist/packages

      # Mark the output file as executable
      - name: Make output file executable
        run: chmod +x dist/packages/RobotLab-X-${{ env.VERSION }}-x86_64.AppImage

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-aws-region

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: your-bucket-name
          SOURCE_DIR: 'path/to/your/files'
