name: Linux Build and Package RobotLab-X

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.18.0]

    env:
      CI: false

    steps:
      - name: Verify Version Input and Set Environment Variable
        run: |
          echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          echo "Passed version is: ${{ inputs.version }}"
          echo "All environment variables:"
          printenv
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install-all

      - name: Run ESLint
        run: yarn lint || true

      - name: Build Server
        run: yarn build-server

      - name: Run tests
        run: |
          cd server
          yarn test

      - name: Package
        run: yarn package-linux

      - name: List dist/packages contents
        run: ls -l dist/packages

      # Mark the output file as executable
      - name: Make output file executable
        run: chmod +x dist/packages/RobotLab-X-${{ env.VERSION }}-x86_64.AppImage

        # Upload to Amazon S3
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'robotlab-x-repo'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'dist/packages/RobotLab-X-${{ env.VERSION }}-x86_64.AppImage'      # optional: defaults to entire repository

      # - name: Copy a file from s3
      #   uses: prewk/s3-cp-action@v2
      #   with:
      #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     source: 's3://some-bucket/something-remote'
      #     dest: './something-local'

      # # Upload to Amazon S3
      # - name: Upload to Amazon S3
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: us-east-1
      #   run: |
      #     aws s3 cp dist/packages/RobotLab-X-${{ env.VERSION }}-x86_64.AppImage s3://robotlab-x-repo/RobotLab-X-${{ env.VERSION }}-x86_64.AppImage


