name: Linux Build and Package RobotLab-X

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

env:
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.18.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install-all

      - name: Run ESLint
        run: yarn lint || true

      - name: Build Server
        run: yarn build-server

      - name: Run tests
        run: |
          cd server
          yarn test

      - name: Package
        run: yarn package-linux

      - name: List dist/packages contents
        run: ls -l dist/packages

      # Mark the output file as executable
      - name: Make output file executable
        run: chmod +x dist/packages/RobotLab-X-${{ inputs.version }}-x86_64.AppImage

      # Upload to Amazon S3
      - name: Upload to Amazon S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 cp dist/packages/RobotLab-X-${{ inputs.version }}-x86_64.AppImage s3://your-bucket-name/path/to/folder/
