name: Linux Arm64 Build and Package RobotLab-X

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.18.0]

    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Print system info
        run: |
          uname -a
          lscpu
          cat /etc/os-release

      - name: Verify Version Input and Set Environment Variable
        run: |
          echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          echo "Passed version is: ${{ inputs.version }}"
          echo "All environment variables:"
          printenv
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install-all

      - name: Run ESLint
        run: yarn lint || true

      - name: Build Server
        run: yarn build-server

      - name: Run tests
        run: |
          cd server
          yarn test

      - name: PreBuild clean
        run: rm -rf ~/.npm/_prebuilds

      - name: Package
        run: yarn package-linux-arm64

      - name: List dist/packages contents
        run: ls -l dist/packages

      # Mark the output file as executable
      - name: Make output file executable
        run: chmod +x dist/packages/RobotLab-X-${{ env.VERSION }}-arm64.AppImage

      # - name: Make version folder and move executable to that folder
      #   run: mkdir -p artifact/RobotLab-X-0.9.${{ github.run_number }} && mv dist/packages/RobotLab-X-0.9.${{ github.run_number }}.AppImage artifact/RobotLab-X-0.9.${{ github.run_number }}/RobotLab-X-0.9.${{ github.run_number }}-arm64.AppImage

      - name: Upload to Amazon S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          aws s3 cp dist/packages/RobotLab-X-${{ env.VERSION }}-arm64.AppImage s3://robotlab-x-repo/RobotLab-X-${{ env.VERSION }}-arm64.AppImage


