name: Linux Build and Package RobotLab-X

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.7.2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install-all

      - name: Bump version
        id: bump_version
        run: |
          BUILD_NUMBER=${{ github.run_number }}
          VERSION="0.9.${BUILD_NUMBER}"
          PRODUCT_NAME="robotlab-x-${VERSION}"
          echo "Bumping version to $VERSION"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          echo "VERSION=0.9.${{ github.run_number }}" >> $GITHUB_ENV

        # temporarily disabled
        # git add package.json server/package.json client/package.json
        # git commit -m "Bump version to $VERSION"
        # git push origin main

      # Run ESLint but ignore errors
      - name: Run ESLint
        run: yarn lint || true

      - name: Run tests
        run: |
          cd server
          yarn test

      - name: PreBuild
        run: yarn prebuild

      - name: Build
        run: yarn build-linux

      - name: List dist/packages contents
        run: ls -l dist/packages

      - name: Set executable permissions
        run: chmod +x dist/packages/RobotLab-X-0.9.${{ github.run_number }}.AppImage

      - name: Move to version folder
        run: mkdir RobotLab-X-0.9.${{ github.run_number }} && mv dist/packages/RobotLab-X-0.9.${{ github.run_number }}.AppImage RobotLab-X-0.9.${{ github.run_number }}

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v3
        with:
          name: RobotLab-X-0.9.${{ github.run_number }}
          path: RobotLab-X-0.9.${{ github.run_number }}

      # - name: Upload .deb artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: RobotLab-X-0.9.${{ github.run_number }}.deb
      #     path: dist/packages/RobotLab-X-0.9.${{ github.run_number }}.deb

  # release:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: RobotLab-X-${{ env.VERSION }}.AppImage
  #         path: dist/

  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: v${{ env.VERSION }}
  #         release_name: Release v${{ env.VERSION }}
  #         draft: false
  #         prerelease: false

  #     - name: Upload Release Asset
