name: Main Build Workflow

on:
  push:
    branches:
      - main

jobs:
  generate-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Generate Version Number
        id: set-version
        run: |
          BUILD_NUMBER=$(( $GITHUB_RUN_NUMBER + 160 ))
          VERSION="0.9.${BUILD_NUMBER}"
          echo "Generated version: $VERSION"
          echo "::set-output name=version::$VERSION"
        shell: bash

  build-linux:
    needs: generate-version
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit
    with:
      version: ${{ needs.generate-version.outputs.version }}


  # build-windows:
  #   needs: generate-version
  #   uses: ./.github/workflows/build-win.yml
  #   secrets: inherit
  #   with:
  #     version: ${{ needs.generate-version.outputs.version }}
