name: Build Post-Processing

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  post-processing:
    runs-on: ubuntu-latest
    steps:

      - name: Verify Version Input and Set Environment Variable
        run: |
          echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          echo "Passed version is: ${{ inputs.version }}"
          echo "All environment variables:"
          printenv
        shell: bash

      - name: Debug Version Input
        run: |
          echo "Received version: '${{ inputs.version }}'"
          echo "env version: '${{ env.VERSION }}'"

      - name: Create latest.json
        run: |
          echo "{ \"version\": \"${{ env.VERSION }}\" }" > latest.json
          echo "Created latest.json with content:"
          cat latest.json

      - name: Upload latest.json to Amazon S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          aws s3 cp latest.json "s3://robotlab-x-repo/latest.json"

        # refer for discord webhook details to https://gist.github.com/Birdie0/78ee79402a4301b1faf412ab5f1cdcf9
      - name: Send Version to Discord
        run: |
            curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
                  "content": "New Version Deployed: **${{ env.VERSION }}**",
                  "embeds": [
                    {
                      "title": "New Version Deployed: **${{ env.VERSION }}**",
                      "url": "https://robotlab-x.com",
                      "description": "Version [${{ env.VERSION }}](https://robotlab-x.com) has been deployed successfully.",
                      "color": 5814783
                    }
                  ]
                }' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
