name: Windows Build and Package RobotLab-X

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: false

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [21.7.2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: |
          yarn config set network-timeout 600000 -g
          yarn config set registry https://registry.npm.taobao.org
          yarn install-all

      - name: Bump version
        id: bump_version
        run: |
          $BUILD_NUMBER = ${{ github.run_number }}
          $VERSION = "0.9.$BUILD_NUMBER"
          Write-Host "Bumping version to $VERSION"
          npx json -I -f package.json -e "this.version='$VERSION'"
          npx json -I -f server/package.json -e "this.version='$VERSION'"
          npx json -I -f client/package.json -e "this.version='$VERSION'"

      # Run ESLint but ignore errors
      - name: Run ESLint
        run: yarn lint || true

      - name: Run tests
        run: |
          cd server
          yarn test

      - name: Generate the package file
        run: yarn generate-pkg-file

      - name: Build the Electron app for Windows
        run: yarn build-win


      - name: List dist/packages contents
        run: dir dist\\packages

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: RobotLab-X-0.9.${{ github.run_number }}.exe
          path: dist/packages/RobotLab-X-Setup-0.9.${{ github.run_number }}.exe

  # release:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: RobotLab-X-0.9.${{ github.run_number }}.exe
  #         path: dist/

  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: v0.9.${{ github.run_number }}
  #         release_name: Release v0.9.${{ github.run_number }}
  #         draft: false
  #         prerelease: false

  #     - name: Upload Release Asset
  #       uses: actions/upload-release-asset@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         upload_url: ${{ steps.create_release.outputs.upload_url }}
  #         asset_path: dist/packages/RobotLab-X-0.9.${{ github.run_number }}.exe
  #         asset_name: RobotLab-X-0.9.${{ github.run_number }}.exe
  #         asset_content_type: application/octet-stream

