name: Windows Build and Package RobotLab-X


on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.18.0]

    env:
      CI: false

    steps:
      - name: Verify Version Input and Set Environment Variable
        run: |
          echo VERSION=${{ inputs.version }} >> %GITHUB_ENV%
          echo Passed version is: ${{ inputs.version }}
          echo All environment variables:
          set
        shell: cmd

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: |
          yarn config set network-timeout 600000 -g
          yarn config set registry https://registry.npm.taobao.org
          yarn install-all

      - name: Run ESLint
        run: yarn lint || true

      - name: Build Server
        run: yarn build-server
        shell: cmd

      - name: pwd
        run: cd
        shell: cmd

      - name: dir
        run: dir
        shell: cmd

      # - name: Run tests
      #   run: |
      #     cd server
      #     yarn test
      #   shell: cmd
      #   working-directory: ./server

      # - name: Print all environment variables
      #   run: set "VERSION=0.9.${{ github.run_number }}" && set
      #   shell: cmd

      # - name: Package the Electron app for Windows
      #   run: set "VERSION=0.9.${{ github.run_number }}" && yarn package-win
      #   shell: cmd

      - name: List dist/packages contents
        run: dir dist\\packages
        shell: cmd

      # - name: Make version folder and move executable to that folder
      #   run: mkdir -p artifact/RobotLab-X-0.9.${{ github.run_number }} && mv dist/packages/RobotLab-X-Setup-0.9.${{ github.run_number }}.exe artifact/RobotLab-X-0.9.${{ github.run_number }}

      - name: Upload to Amazon S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          aws s3 cp dist/packages/RobotLab-X-${{ env.VERSION }}-x86_64.AppImage s3://robotlab-x-repo/RobotLab-X-${{ env.VERSION }}-x86_64.AppImage


