name: Linux Build and Package RobotLab-X

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.18.0]

    env:
      CI: false

    steps:
      - name: Verify Version Input and Set Environment Variable
        run: |
          echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          echo "Passed version is: ${{ inputs.version }}"
          echo "All environment variables:"
          printenv
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install-all

      # - name: Run ESLint
      #   run: yarn lint || true

      # - name: Build and Install Client
      #   run: |
      #     yarn build-client
      #     yarn install-client

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: client-artifact
          path: server/dist/client

      - name: Build Server
        run: yarn build-server

      - name: Run tests
        run: |
          cd server
          yarn test

      - name: Package
        run: yarn package-linux

      - name: Make output file executable
        run: chmod +x "dist/packages/robotlab-x-${{ env.VERSION }}-x86_64.AppImage"

      - name: Create versioned folder and move artifact
        run: |
          mkdir -p "dist/packages/robotLab-X-${{ env.VERSION }}"
          mv "dist/packages/robotlab-x-${{ env.VERSION }}-x86_64.AppImage" "dist/packages/robotLab-X-${{ env.VERSION }}/"

      - name: Zip the versioned folder
        run: |
          cd dist/packages
          zip -r "robotlab-X-${{ env.VERSION }}-linux-x86_64.zip" "robotLab-X-${{ env.VERSION }}"

      - name: List dist/packages contents
        run: ls -l dist/packages


      - name: Upload to Amazon S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          aws s3 cp "dist/packages/robotlab-X-${{ env.VERSION }}-linux-x86_64.zip" "s3://robotlab-x-repo/robotlab-X-${{ env.VERSION }}-linux-x86_64.zip"


