name: Build Post-Processing

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  post-processing:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Version Input
        run: |
          echo "Received version: '${{ inputs.version }}'"

      - name: Create latest.json
        run: |
          echo "{ \"version\": \"${{ inputs.version }}\" }" > latest.json
          echo "Created latest.json with content:"
          cat latest.json

      - name: Upload latest.json to Amazon S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          aws s3 cp latest.json "s3://robotlab-x-repo/latest.json"
