name: Main Build Workflow

on:
  push:
    branches:
      - main

jobs:
  generate-version:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.18.0]

    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Generate Version Number
        id: set-version
        run: |
          BUILD_NUMBER=$(( $GITHUB_RUN_NUMBER + 160 ))
          VERSION="0.9.${BUILD_NUMBER}"
          echo "Generated version: ${VERSION}"
          echo "::set-output name=version::${VERSION}"
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: cd client && yarn install

      - name: Run ESLint
        run: yarn lint || true

      - name: Build and Install Client
        run: |
          yarn build-client
          yarn install-client


  build-linux:
    needs: generate-version
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit
    with:
      version: ${{ needs.generate-version.outputs.version }}

  build-linux-arm64:
    needs: generate-version
    uses: ./.github/workflows/build-linux-arm64.yml
    secrets: inherit
    with:
      version: ${{ needs.generate-version.outputs.version }}

  build-windows:
    needs: generate-version
    uses: ./.github/workflows/build-win.yml
    secrets: inherit
    with:
      version: ${{ needs.generate-version.outputs.version }}




  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: v${{ env.VERSION }}
  #         release_name: Release v${{ env.VERSION }}
  #         draft: false
  #         prerelease: false
