openapi: 3.0.3
info:
  title: API Documentation
  version: 1.0.0
servers:
  - url: http://localhost:3001/v1
    description: Local development server
components:
  schemas:
    $schema: http://json-schema.org/draft-07/schema#
    definitions:
      A<object>:
        description: An AsyncIterator which can be aborted
        properties:
          abortController: {}
          doneCallback: {}
          itr: {}
        type: object
      a:
        properties:
          fetch:
            type: object
          host:
            type: string
          proxy:
            type: boolean
        type: object
    properties:
      config:
        $ref: "#/definitions/a"
      fetch:
        type: object
      ongoingStreamedRequests:
        items:
          $ref: "#/definitions/A<object>"
        type: array
    type: object
paths:
  /applyConfig:
    put:
      summary: Executes applyConfig method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: any
            example:
              - config
      responses:
        "200":
          description: applyConfig executed successfully
    get:
      summary: Fetch information for applyConfig
      description: HTTP GET for applyConfig
      parameters:
        - name: config
          in: query
          required: true
          schema:
            type: any
          description: Parameter config
      responses:
        "200":
          description: Details for applyConfig fetched successfully
  /attachNeoPixel:
    put:
      summary: Executes attachNeoPixel method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: string
                - type: integer
            example:
              - pin
              - length
      responses:
        "200":
          description: attachNeoPixel executed successfully
    get:
      summary: Fetch information for attachNeoPixel
      description: HTTP GET for attachNeoPixel
      parameters:
        - name: pin
          in: query
          required: true
          schema:
            type: string
          description: Parameter pin
        - name: length
          in: query
          required: true
          schema:
            type: integer
          description: Parameter length
      responses:
        "200":
          description: Details for attachNeoPixel fetched successfully
  /connect:
    put:
      summary: Executes connect method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: string
            example:
              - port
      responses:
        "200":
          description: connect executed successfully
    get:
      summary: Fetch information for connect
      description: HTTP GET for connect
      parameters:
        - name: port
          in: query
          required: true
          schema:
            type: string
          description: Parameter port
      responses:
        "200":
          description: Details for connect fetched successfully
  /createPins:
    put:
      summary: Executes createPins method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: []
      responses:
        "200":
          description: createPins executed successfully
    get:
      summary: Fetch information for createPins
      description: HTTP GET for createPins
      parameters: []
      responses:
        "200":
          description: Details for createPins fetched successfully
  /disconnect:
    put:
      summary: Executes disconnect method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: []
      responses:
        "200":
          description: disconnect executed successfully
    get:
      summary: Fetch information for disconnect
      description: HTTP GET for disconnect
      parameters: []
      responses:
        "200":
          description: Details for disconnect fetched successfully
  /getBoardInfo:
    put:
      summary: Executes getBoardInfo method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: []
      responses:
        "200":
          description: getBoardInfo executed successfully
    get:
      summary: Fetch information for getBoardInfo
      description: HTTP GET for getBoardInfo
      parameters: []
      responses:
        "200":
          description: Details for getBoardInfo fetched successfully
  /getNeoPixel:
    put:
      summary: Executes getNeoPixel method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: string
            example:
              - pin
      responses:
        "200":
          description: getNeoPixel executed successfully
    get:
      summary: Fetch information for getNeoPixel
      description: HTTP GET for getNeoPixel
      parameters:
        - name: pin
          in: query
          required: true
          schema:
            type: string
          description: Parameter pin
      responses:
        "200":
          description: Details for getNeoPixel fetched successfully
  /getPins:
    put:
      summary: Executes getPins method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: []
      responses:
        "200":
          description: getPins executed successfully
    get:
      summary: Fetch information for getPins
      description: HTTP GET for getPins
      parameters: []
      responses:
        "200":
          description: Details for getPins fetched successfully
  /getPorts:
    put:
      summary: Executes getPorts method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: []
      responses:
        "200":
          description: getPorts executed successfully
    get:
      summary: Fetch information for getPorts
      description: HTTP GET for getPorts
      parameters: []
      responses:
        "200":
          description: Details for getPorts fetched successfully
  /neoPixelColor:
    put:
      summary: Executes neoPixelColor method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: string
                - type: any
            example:
              - pin
              - color
      responses:
        "200":
          description: neoPixelColor executed successfully
    get:
      summary: Fetch information for neoPixelColor
      description: HTTP GET for neoPixelColor
      parameters:
        - name: pin
          in: query
          required: true
          schema:
            type: string
          description: "- pin number of the neopixel"
        - name: color
          in: query
          required: true
          schema:
            type: any
          description: '- can be of the form "#ff0000", "rgb(0, 255, 0)", or [255, 255, 0]'
      responses:
        "200":
          description: Details for neoPixelColor fetched successfully
  /neoPixelFlash:
    put:
      summary: Executes neoPixelFlash method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: Flash
            example:
              - flash
      responses:
        "200":
          description: neoPixelFlash executed successfully
    get:
      summary: Fetch information for neoPixelFlash
      description: HTTP GET for neoPixelFlash
      parameters:
        - name: flash
          in: query
          required: true
          schema:
            type: Flash
          description: Parameter flash
      responses:
        "200":
          description: Details for neoPixelFlash fetched successfully
  /neoPixelOff:
    put:
      summary: Executes neoPixelOff method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: string
            example:
              - pin
      responses:
        "200":
          description: neoPixelOff executed successfully
    get:
      summary: Fetch information for neoPixelOff
      description: HTTP GET for neoPixelOff
      parameters:
        - name: pin
          in: query
          required: true
          schema:
            type: string
          description: Parameter pin
      responses:
        "200":
          description: Details for neoPixelOff fetched successfully
  /neoPixelSet:
    put:
      summary: Executes neoPixelSet method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: string
                - type: integer
                - type: any
            example:
              - pin
              - number
              - color
      responses:
        "200":
          description: neoPixelSet executed successfully
    get:
      summary: Fetch information for neoPixelSet
      description: HTTP GET for neoPixelSet
      parameters:
        - name: pin
          in: query
          required: true
          schema:
            type: string
          description: Parameter pin
        - name: number
          in: query
          required: true
          schema:
            type: integer
          description: Parameter number
        - name: color
          in: query
          required: true
          schema:
            type: any
          description: Parameter color
      responses:
        "200":
          description: Details for neoPixelSet fetched successfully
  /neoPixelShift:
    put:
      summary: Executes neoPixelShift method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: string
                - type: integer
                - type: boolean
                - type: integer
            example:
              - pin
              - amt
              - wrap
              - interval
      responses:
        "200":
          description: neoPixelShift executed successfully
    get:
      summary: Fetch information for neoPixelShift
      description: HTTP GET for neoPixelShift
      parameters:
        - name: pin
          in: query
          required: true
          schema:
            type: string
          description: Parameter pin
        - name: amt
          in: query
          required: true
          schema:
            type: integer
          description: Parameter amt
        - name: wrap
          in: query
          required: true
          schema:
            type: boolean
          description: Parameter wrap
        - name: interval
          in: query
          required: true
          schema:
            type: integer
          description: Parameter interval
      responses:
        "200":
          description: Details for neoPixelShift fetched successfully
  /onNeoPixel:
    put:
      summary: Executes onNeoPixel method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: string
                - type: integer
                - type: integer
                - type: integer
                - type: integer
            example:
              - pin
              - r
              - g
              - b
              - w
      responses:
        "200":
          description: onNeoPixel executed successfully
    get:
      summary: Fetch information for onNeoPixel
      description: HTTP GET for onNeoPixel
      parameters:
        - name: pin
          in: query
          required: true
          schema:
            type: string
          description: Parameter pin
        - name: r
          in: query
          required: true
          schema:
            type: integer
          description: Parameter r
        - name: g
          in: query
          required: true
          schema:
            type: integer
          description: Parameter g
        - name: b
          in: query
          required: true
          schema:
            type: integer
          description: Parameter b
        - name: w
          in: query
          required: true
          schema:
            type: integer
          description: Parameter w
      responses:
        "200":
          description: Details for onNeoPixel fetched successfully
  /onServoMoveTo:
    put:
      summary: Executes onServoMoveTo method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: ServoMove
            example:
              - servoMove
      responses:
        "200":
          description: onServoMoveTo executed successfully
    get:
      summary: Fetch information for onServoMoveTo
      description: HTTP GET for onServoMoveTo
      parameters:
        - name: servoMove
          in: query
          required: true
          schema:
            type: ServoMove
          description: Parameter servoMove
      responses:
        "200":
          description: Details for onServoMoveTo fetched successfully
  /printServoDetails:
    put:
      summary: Executes printServoDetails method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: any
            example:
              - servo
      responses:
        "200":
          description: printServoDetails executed successfully
    get:
      summary: Fetch information for printServoDetails
      description: HTTP GET for printServoDetails
      parameters:
        - name: servo
          in: query
          required: true
          schema:
            type: any
          description: Parameter servo
      responses:
        "200":
          description: Details for printServoDetails fetched successfully
  /servoWrite:
    put:
      summary: Executes servoWrite method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: string
                - type: integer
                - type: integer
            example:
              - pin
              - angle
              - speed
      responses:
        "200":
          description: servoWrite executed successfully
    get:
      summary: Fetch information for servoWrite
      description: HTTP GET for servoWrite
      parameters:
        - name: pin
          in: query
          required: true
          schema:
            type: string
          description: Parameter pin
        - name: angle
          in: query
          required: true
          schema:
            type: integer
          description: Parameter angle
        - name: speed
          in: query
          required: true
          schema:
            type: integer
          description: Parameter speed
      responses:
        "200":
          description: Details for servoWrite fetched successfully
  /startService:
    put:
      summary: Executes startService method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: []
      responses:
        "200":
          description: startService executed successfully
    get:
      summary: Fetch information for startService
      description: HTTP GET for startService
      parameters: []
      responses:
        "200":
          description: Details for startService fetched successfully
  /stopService:
    put:
      summary: Executes stopService method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: []
      responses:
        "200":
          description: stopService executed successfully
    get:
      summary: Fetch information for stopService
      description: HTTP GET for stopService
      parameters: []
      responses:
        "200":
          description: Details for stopService fetched successfully
  /toJSON:
    put:
      summary: Executes toJSON method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: []
      responses:
        "200":
          description: toJSON executed successfully
    get:
      summary: Fetch information for toJSON
      description: HTTP GET for toJSON
      parameters: []
      responses:
        "200":
          description: Details for toJSON fetched successfully
  /write:
    put:
      summary: Executes write method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: integer
                - type: integer
            example:
              - pin
              - value
      responses:
        "200":
          description: write executed successfully
    get:
      summary: Fetch information for write
      description: HTTP GET for write
      parameters:
        - name: pin
          in: query
          required: true
          schema:
            type: integer
          description: Parameter pin
        - name: value
          in: query
          required: true
          schema:
            type: integer
          description: Parameter value
      responses:
        "200":
          description: Details for write fetched successfully
tags: []
