openapi: 3.0.3
info:
  title: API Documentation
  version: 1.0.0
servers:
  - url: http://localhost:3001/v1
    description: Local development server
components:
  schemas:
    $schema: http://json-schema.org/draft-07/schema#
    definitions:
      A<object>:
        description: An AsyncIterator which can be aborted
        properties:
          abortController: {}
          doneCallback: {}
          itr: {}
        type: object
      a:
        properties:
          fetch:
            type: object
          host:
            type: string
          proxy:
            type: boolean
        type: object
    properties:
      config:
        $ref: "#/definitions/a"
      fetch:
        type: object
      ongoingStreamedRequests:
        items:
          $ref: "#/definitions/A<object>"
        type: array
    type: object
paths:
  /createAndStartContainer:
    put:
      summary: Executes createAndStartContainer method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: string
                - type: string
            example:
              - imageName
              - containerName
      responses:
        "200":
          description: createAndStartContainer executed successfully
    get:
      summary: Fetch information for createAndStartContainer
      description: HTTP GET for createAndStartContainer
      parameters:
        - name: imageName
          in: query
          required: true
          schema:
            type: string
          description: Parameter imageName
        - name: containerName
          in: query
          required: true
          schema:
            type: string
          description: Parameter containerName
      responses:
        "200":
          description: Details for createAndStartContainer fetched successfully
  /deleteContainer:
    put:
      summary: Executes deleteContainer method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: string
            example:
              - containerId
      responses:
        "200":
          description: deleteContainer executed successfully
    get:
      summary: Fetch information for deleteContainer
      description: HTTP GET for deleteContainer
      parameters:
        - name: containerId
          in: query
          required: true
          schema:
            type: string
          description: Parameter containerId
      responses:
        "200":
          description: Details for deleteContainer fetched successfully
  /deleteImage:
    put:
      summary: Executes deleteImage method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: string
            example:
              - imageId
      responses:
        "200":
          description: deleteImage executed successfully
    get:
      summary: Fetch information for deleteImage
      description: HTTP GET for deleteImage
      parameters:
        - name: imageId
          in: query
          required: true
          schema:
            type: string
          description: Parameter imageId
      responses:
        "200":
          description: Details for deleteImage fetched successfully
  /getImages:
    put:
      summary: Executes getImages method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: []
      responses:
        "200":
          description: getImages executed successfully
    get:
      summary: Fetch information for getImages
      description: HTTP GET for getImages
      parameters: []
      responses:
        "200":
          description: Details for getImages fetched successfully
  /ps:
    put:
      summary: Executes ps method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: []
      responses:
        "200":
          description: ps executed successfully
    get:
      summary: Fetch information for ps
      description: HTTP GET for ps
      parameters: []
      responses:
        "200":
          description: Details for ps fetched successfully
  /publishImages:
    put:
      summary: Executes publishImages method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: any
            example:
              - images
      responses:
        "200":
          description: publishImages executed successfully
    get:
      summary: Fetch information for publishImages
      description: HTTP GET for publishImages
      parameters:
        - name: images
          in: query
          required: true
          schema:
            type: any
          description: Parameter images
      responses:
        "200":
          description: Details for publishImages fetched successfully
  /publishPs:
    put:
      summary: Executes publishPs method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: []
      responses:
        "200":
          description: publishPs executed successfully
    get:
      summary: Fetch information for publishPs
      description: HTTP GET for publishPs
      parameters: []
      responses:
        "200":
          description: Details for publishPs fetched successfully
  /pullImage:
    put:
      summary: Executes pullImage method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: string
            example:
              - imageName
      responses:
        "200":
          description: pullImage executed successfully
    get:
      summary: Fetch information for pullImage
      description: HTTP GET for pullImage
      parameters:
        - name: imageName
          in: query
          required: true
          schema:
            type: string
          description: Parameter imageName
      responses:
        "200":
          description: Details for pullImage fetched successfully
  /showAll:
    put:
      summary: Executes showAll method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: boolean
            example:
              - all
      responses:
        "200":
          description: showAll executed successfully
    get:
      summary: Fetch information for showAll
      description: HTTP GET for showAll
      parameters:
        - name: all
          in: query
          required: true
          schema:
            type: boolean
          description: Parameter all
      responses:
        "200":
          description: Details for showAll fetched successfully
  /startPs:
    put:
      summary: Executes startPs method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: []
      responses:
        "200":
          description: startPs executed successfully
    get:
      summary: Fetch information for startPs
      description: HTTP GET for startPs
      parameters: []
      responses:
        "200":
          description: Details for startPs fetched successfully
  /startService:
    put:
      summary: Executes startService method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: []
      responses:
        "200":
          description: startService executed successfully
    get:
      summary: Fetch information for startService
      description: HTTP GET for startService
      parameters: []
      responses:
        "200":
          description: Details for startService fetched successfully
  /stopPs:
    put:
      summary: Executes stopPs method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: []
      responses:
        "200":
          description: stopPs executed successfully
    get:
      summary: Fetch information for stopPs
      description: HTTP GET for stopPs
      parameters: []
      responses:
        "200":
          description: Details for stopPs fetched successfully
  /stopService:
    put:
      summary: Executes stopService method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: []
      responses:
        "200":
          description: stopService executed successfully
    get:
      summary: Fetch information for stopService
      description: HTTP GET for stopService
      parameters: []
      responses:
        "200":
          description: Details for stopService fetched successfully
  /toJSON:
    put:
      summary: Executes toJSON method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: []
      responses:
        "200":
          description: toJSON executed successfully
    get:
      summary: Fetch information for toJSON
      description: HTTP GET for toJSON
      parameters: []
      responses:
        "200":
          description: Details for toJSON fetched successfully
tags: []
