openapi: 3.0.3
info:
  title: API Documentation
  version: 1.0.0
servers:
  - url: http://localhost:3001/v1
    description: Local development server
components:
  schemas:
    $schema: http://json-schema.org/draft-07/schema#
    definitions:
      A<object>:
        description: An AsyncIterator which can be aborted
        properties:
          abortController: {}
          doneCallback: {}
          itr: {}
        type: object
      a:
        properties:
          fetch:
            type: object
          host:
            type: string
          proxy:
            type: boolean
        type: object
    properties:
      config:
        $ref: "#/definitions/a"
      fetch:
        type: object
      ongoingStreamedRequests:
        items:
          $ref: "#/definitions/A<object>"
        type: array
    type: object
paths:
  /applyConfig:
    put:
      summary: Executes applyConfig method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: any
            example:
              - config
      responses:
        "200":
          description: applyConfig executed successfully
    get:
      summary: Fetch information for applyConfig
      description: HTTP GET for applyConfig
      parameters:
        - name: config
          in: query
          required: true
          schema:
            type: any
          description: Parameter config
      responses:
        "200":
          description: Details for applyConfig fetched successfully
  /fetchVoices:
    put:
      summary: Executes fetchVoices method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: []
      responses:
        "200":
          description: fetchVoices executed successfully
    get:
      summary: Fetch information for fetchVoices
      description: HTTP GET for fetchVoices
      parameters: []
      responses:
        "200":
          description: Details for fetchVoices fetched successfully
  /initializePollyClient:
    put:
      summary: Executes initializePollyClient method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: []
      responses:
        "200":
          description: initializePollyClient executed successfully
    get:
      summary: Fetch information for initializePollyClient
      description: HTTP GET for initializePollyClient
      parameters: []
      responses:
        "200":
          description: Details for initializePollyClient fetched successfully
  /onText:
    put:
      summary: Executes onText method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: string
            example:
              - text
      responses:
        "200":
          description: onText executed successfully
    get:
      summary: Fetch information for onText
      description: HTTP GET for onText
      parameters:
        - name: text
          in: query
          required: true
          schema:
            type: string
          description: Parameter text
      responses:
        "200":
          description: Details for onText fetched successfully
  /publishPlayAudioFile:
    put:
      summary: Executes publishPlayAudioFile method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: string
            example:
              - filename
      responses:
        "200":
          description: publishPlayAudioFile executed successfully
    get:
      summary: Fetch information for publishPlayAudioFile
      description: HTTP GET for publishPlayAudioFile
      parameters:
        - name: filename
          in: query
          required: true
          schema:
            type: string
          description: Parameter filename
      responses:
        "200":
          description: Details for publishPlayAudioFile fetched successfully
  /publishSpeaking:
    put:
      summary: Executes publishSpeaking method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: string
            example:
              - text
      responses:
        "200":
          description: publishSpeaking executed successfully
    get:
      summary: Fetch information for publishSpeaking
      description: HTTP GET for publishSpeaking
      parameters:
        - name: text
          in: query
          required: true
          schema:
            type: string
          description: Parameter text
      responses:
        "200":
          description: Details for publishSpeaking fetched successfully
  /speak:
    put:
      summary: Executes speak method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: string
            example:
              - text
      responses:
        "200":
          description: speak executed successfully
    get:
      summary: Fetch information for speak
      description: HTTP GET for speak
      parameters:
        - name: text
          in: query
          required: true
          schema:
            type: string
          description: Parameter text
      responses:
        "200":
          description: Details for speak fetched successfully
  /startService:
    put:
      summary: Executes startService method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: []
      responses:
        "200":
          description: startService executed successfully
    get:
      summary: Fetch information for startService
      description: HTTP GET for startService
      parameters: []
      responses:
        "200":
          description: Details for startService fetched successfully
  /toJSON:
    put:
      summary: |-
        Serializes the Polly instance to JSON.
        Excludes intervalId from serialization.
      description: |-
        Serializes the Polly instance to JSON.
        Excludes intervalId from serialization.
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: []
      responses:
        "200":
          description: The serialized Polly instance.
    get:
      summary: Fetch information for toJSON
      description: HTTP GET for toJSON
      parameters: []
      responses:
        "200":
          description: The serialized Polly instance.
tags: []
