openapi: 3.0.3
info:
  title: API Documentation
  version: 1.0.0
servers:
  - url: http://localhost:3001/v1
    description: Local development server
components:
  schemas:
    $schema: http://json-schema.org/draft-07/schema#
    definitions:
      A<object>:
        description: An AsyncIterator which can be aborted
        properties:
          abortController: {}
          doneCallback: {}
          itr: {}
        type: object
      a:
        properties:
          fetch:
            type: object
          host:
            type: string
          proxy:
            type: boolean
        type: object
    properties:
      config:
        $ref: "#/definitions/a"
      fetch:
        type: object
      ongoingStreamedRequests:
        items:
          $ref: "#/definitions/A<object>"
        type: array
    type: object
paths:
  /sendRemote:
    put:
      summary: |-
        Overriding sendRemote - all UIs are remote proxies,
        however the funtionality of interest besides displaying is
        configuration, which a RobotLabXUI does not have. The
        proxy is the only way to send/save/apply configuration to this UI.

        So, we intercept the these messages here.
      description: |-
        Overriding sendRemote - all UIs are remote proxies,
        however the funtionality of interest besides displaying is
        configuration, which a RobotLabXUI does not have. The
        proxy is the only way to send/save/apply configuration to this UI.

        So, we intercept the these messages here.
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: Message
            example:
              - msg
      responses:
        "200":
          description: sendRemote executed successfully
    get:
      summary: Fetch information for sendRemote
      description: HTTP GET for sendRemote
      parameters:
        - name: msg
          in: query
          required: true
          schema:
            type: Message
          description: Parameter msg
      responses:
        "200":
          description: Details for sendRemote fetched successfully
  /startService:
    put:
      summary: Executes startService method
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: []
      responses:
        "200":
          description: startService executed successfully
    get:
      summary: Fetch information for startService
      description: HTTP GET for startService
      parameters: []
      responses:
        "200":
          description: Details for startService fetched successfully
  /toJSON:
    put:
      summary: Serializes the RobotLabXUI instance to JSON.
      description: Serializes the RobotLabXUI instance to JSON.
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: []
      responses:
        "200":
          description: The serialized RobotLabXUI instance.
    get:
      summary: Fetch information for toJSON
      description: HTTP GET for toJSON
      parameters: []
      responses:
        "200":
          description: The serialized RobotLabXUI instance.
tags: []
