openapi: 3.0.3
info:
  title: API Documentation
  version: 1.0.0
servers:
  - url: http://localhost:3001/v1
    description: Local development server
components:
  schemas:
    $schema: http://json-schema.org/draft-07/schema#
    definitions:
      A<object>:
        description: An AsyncIterator which can be aborted
        properties:
          abortController: {}
          doneCallback: {}
          itr: {}
        type: object
      a:
        properties:
          fetch:
            type: object
          host:
            type: string
          proxy:
            type: boolean
        type: object
    properties:
      config:
        $ref: "#/definitions/a"
      fetch:
        type: object
      ongoingStreamedRequests:
        items:
          $ref: "#/definitions/A<object>"
        type: array
    type: object
paths:
  /publishText:
    put:
      summary: Publishes the current epoch time.
      description: Publishes the current epoch time.
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                - type: string
            example:
              - text
      responses:
        "200":
          description: The current epoch time.
    get:
      summary: Fetch information for publishText
      description: HTTP GET for publishText
      parameters:
        - name: text
          in: query
          required: true
          schema:
            type: string
          description: Parameter text
      responses:
        "200":
          description: The current epoch time.
  /toJSON:
    put:
      summary: |-
        Serializes the WebkitSpeechRecognition instance to JSON.
        Excludes intervalId from serialization.
      description: |-
        Serializes the WebkitSpeechRecognition instance to JSON.
        Excludes intervalId from serialization.
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: []
            example: []
      responses:
        "200":
          description: The serialized WebkitSpeechRecognition instance.
    get:
      summary: Fetch information for toJSON
      description: HTTP GET for toJSON
      parameters: []
      responses:
        "200":
          description: The serialized WebkitSpeechRecognition instance.
tags: []
